#include "caption_renderer.hpp"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <cmath>

namespace hyper {

CaptionRenderer::CaptionRenderer(int width, int height, CaptionSize size, CaptionStyle style)
    : m_width(width), m_height(height), m_size(size), m_style(style) {
}

void CaptionRenderer::setResolution(int width, int height) {
    m_width = width;
    m_height = height;
}

void CaptionRenderer::setSize(CaptionSize size) {
    m_size = size;
}

void CaptionRenderer::setStyle(CaptionStyle style) {
    m_style = style;
}

void CaptionRenderer::addSegment(const CaptionSegment& segment) {
    m_segments.push_back(segment);
}

void CaptionRenderer::setSegments(const std::vector<CaptionSegment>& segments) {
    m_segments = segments;
}

int CaptionRenderer::calculateFontSize() const {
    // Exact mapping relative to 1080p horizontal (1920x1080):
    // Small: 28px, Medium: 42px, Large: 56px
    // For vertical 9:16 (1080x1920), height is 1920, so we scale by height / 1080.
    double base = 42.0;
    switch (m_size) {
        case CaptionSize::Small:
            base = 28.0;
            break;
        case CaptionSize::Medium:
            base = 42.0;
            break;
        case CaptionSize::Large:
            base = 56.0;
            break;
    }

    // Reference resolution is 1080p
    double refHeight = (m_height > m_width) ? 1920.0 : 1080.0;
    double scale = static_cast<double>(m_height) / refHeight;

    if (m_height > m_width) {
        // Vertical mobile view (e.g. 1080x1920) benefits from slightly larger legible text
        // Small: 48px, Medium: 72px, Large: 96px on 1080x1920
        base = (m_size == CaptionSize::Small) ? 48.0 :
               (m_size == CaptionSize::Medium) ? 72.0 : 96.0;
        scale = static_cast<double>(m_height) / 1920.0;
    }

    int result = static_cast<int>(std::round(base * (scale > 0 ? scale : 1.0)));
    return std::max(result, 16);
}

std::string CaptionRenderer::formatTimeAss(double seconds) const {
    if (seconds < 0) seconds = 0;
    int total_cs = static_cast<int>(std::round(seconds * 100.0));
    int cs = total_cs % 100;
    int total_s = total_cs / 100;
    int s = total_s % 60;
    int total_m = total_s / 60;
    int m = total_m % 60;
    int h = total_m / 60;

    std::ostringstream oss;
    oss << h << ":"
        << std::setw(2) << std::setfill('0') << m << ":"
        << std::setw(2) << std::setfill('0') << s << "."
        << std::setw(2) << std::setfill('0') << cs;
    return oss.str();
}

std::string CaptionRenderer::generateAssContent() const {
    int fontSize = calculateFontSize();
    int outline = (m_height > 1080) ? 5 : 3;
    int shadow = (m_height > 1080) ? 3 : 2;
    int marginV = (m_height > m_width) ? static_cast<int>(m_height * 0.18) : static_cast<int>(m_height * 0.08);

    // Color definitions (ASS uses &HAABBGGRR)
    // Primary: White (&H00FFFFFF)
    // Active Karaoke Highlight: Vivid Golden Yellow (&H0000E6FF) or Neon Cyan
    std::string highlightColor = "&H0000E6FF"; // Vibrant Golden Yellow in BGR
    std::string dimColor = "&H00C0C0C0";       // Soft white-grey for upcoming words

    if (m_style == CaptionStyle::Bold) {
        highlightColor = "&H0000FFFF"; // Bright Cyan in BGR
        outline += 1;
    } else if (m_style == CaptionStyle::Minimal) {
        highlightColor = "&H00FFFFFF";
        shadow = 1;
    }

    std::ostringstream ss;
    ss << "[Script Info]\n"
       << "; Script generated by HyperEditor C++ Caption Engine\n"
       << "Title: Hyper Copilot Dynamic Burn-In Captions\n"
       << "ScriptType: v4.00+\n"
       << "WrapStyle: 0\n"
       << "ScaledBorderAndShadow: yes\n"
       << "PlayResX: " << m_width << "\n"
       << "PlayResY: " << m_height << "\n\n"
       << "[V4+ Styles]\n"
       << "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
       << "Style: Default,DejaVu Sans," << fontSize << ",&H00FFFFFF,&H0000FFFF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,"
       << outline << "," << shadow << ",2,30,30," << marginV << ",1\n\n"
       << "[Events]\n"
       << "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n";

    for (const auto& seg : m_segments) {
        if (seg.words.empty()) {
            // Fallback for segment without word timings
            ss << "Dialogue: 0," << formatTimeAss(seg.start_time) << ","
               << formatTimeAss(seg.end_time) << ",Default,,0,0,0,,"
               << "{\\an2}" << seg.full_text << "\n";
            continue;
        }

        // Real-time word-level synchronization (Karaoke highlight)
        // For each active word in the segment, generate a dialogue line with the active word illuminated
        for (size_t i = 0; i < seg.words.size(); ++i) {
            double wordStart = seg.words[i].start_time;
            double wordEnd = seg.words[i].end_time;
            if (wordEnd <= wordStart) {
                wordEnd = wordStart + 0.25;
            }

            // Cap within segment bounds
            wordStart = std::max(wordStart, seg.start_time);
            wordEnd = std::min(wordEnd, seg.end_time);

            if (wordEnd <= wordStart) continue;

            std::ostringstream line;
            line << "Dialogue: 0," << formatTimeAss(wordStart) << ","
                 << formatTimeAss(wordEnd) << ",Default,,0,0,0,,{\\an2}";

            for (size_t j = 0; j < seg.words.size(); ++j) {
                const auto& w = seg.words[j];
                if (j == i) {
                    // Active word: highlighted with vivid color and bold accent
                    line << "{\\c" << highlightColor << "}{\\b1}" << w.word << "{\\b0}{\\c&H00FFFFFF&}";
                } else if (j < i) {
                    // Spoken words: standard white
                    line << "{\\c&H00FFFFFF&}" << w.word;
                } else {
                    // Upcoming words: dimmed for rhythm
                    line << "{\\c" << dimColor << "}" << w.word << "{\\c&H00FFFFFF&}";
                }

                if (j + 1 < seg.words.size()) {
                    line << " ";
                }
            }
            ss << line.str() << "\n";
        }
    }

    return ss.str();
}

bool CaptionRenderer::exportAssFile(const std::string& filePath) const {
    std::ofstream out(filePath);
    if (!out.is_open()) return false;
    out << generateAssContent();
    return true;
}

std::string CaptionRenderer::getFfmpegFilterString(const std::string& assFilePath) const {
    // Escape colons and backslashes for FFmpeg filter syntax
    std::string escaped;
    for (char c : assFilePath) {
        if (c == ':' || c == '\\' || c == '\'') {
            escaped += '\\';
        }
        escaped += c;
    }
    return "ass='" + escaped + "'";
}

CaptionSize CaptionRenderer::parseSize(const std::string& str) {
    std::string lower = str;
    std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
    if (lower.find("small") != std::string::npos || lower == "2") return CaptionSize::Small;
    if (lower.find("large") != std::string::npos || lower == "6") return CaptionSize::Large;
    return CaptionSize::Medium;
}

CaptionStyle CaptionRenderer::parseStyle(const std::string& str) {
    std::string lower = str;
    std::transform(lower.begin(), lower.end(), lower.begin(), ::tolower);
    if (lower.find("bold") != std::string::npos) return CaptionStyle::Bold;
    if (lower.find("minimal") != std::string::npos) return CaptionStyle::Minimal;
    return CaptionStyle::Dynamic;
}

} // namespace hyper
